# Generated by Django 4.0.6 on 2022-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolistmodel_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration date'),
        ),
    ]
