# Generated by Django 4.0.6 on 2022-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_statuses_options_alter_todolistmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='todolist', to='todolist.types'),
        ),
    ]
