# Generated by Django 4.0.6 on 2022-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_projectmodel_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='beginning_date',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
