# Generated by Django 4.0.6 on 2022-07-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_todolistmodel_type_todolistmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodel',
            name='summary',
            field=models.CharField(max_length=30, verbose_name='Summary'),
        ),
    ]
