# Generated by Django 4.0.6 on 2022-08-11 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_remove_projectmodel_beginning_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='users',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
