# Generated by Django 4.0.6 on 2022-07-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todolistmodel_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistmodel',
            old_name='type',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='types',
            old_name='type',
            new_name='types',
        ),
    ]
