# Generated by Django 4.0.6 on 2022-08-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_projectmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'permissions': [('can_change_members', 'Can change members of project')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
